---
- name: Install Python 3 and pip
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - python3
    - python3-dev
    - python3-pip
    - libpq-dev


- name: Update pip and virtualenv
  pip:
    name: "{{ item }}"
    executable: pip3
    state: latest
  with_items:
    - pip
    - virtualenv

- name: Create application env
  command: "virtualenv -p python3 --always-copy {{ virtualenv_dir | quote }}"
  args:
    creates: "{{ virtualenv_dir }}"


- name: Install requirements
  pip:
    requirements: "{{ project_dir }}/{{ requirements_file }}"
    virtualenv: "{{ virtualenv_dir }}"
    virtualenv_python: "python3"
