---
- name: Install Python 3 and pip
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - python3
    - python3-pip


- name: Update pip
  pip:
    name: pip
    executable: pip3
    state: latest